### ISSUE TITLE
Issue on page /docs/TM/tutorials/tutorials.html

### ISSUE THREAD

**Issue by bencreekm** [bHimes/cisTEM_docs#10]
Hello,

I'm not sure the best place to post this issue, but I am trying to use the development version of cisTEM for template matching but running into an error. I'm following the in situ tutorial with an issue at the template search step.

The error is:
No suitable GPU found. Terminating...
Failed Assert at /groups/grigorieff/home/himesb/cisTEM_downstream_bah/src/gpu/DeviceManager.cu:116
void DeviceManager::Init(int)

I'm using the pre-compiled version from 05/05/2021. I'm not able to compile the most recent source code that is linked in the tutorial so have not tried that version. I'm running Ubuntu 18.04 with CUDA Version 11.3, Driver Version 465.19.01. We are using an NVIDA Quadro P4000 GPU.

Thanks!

**Comment by bHimes** [comment]
In principle 8Gb of memory is enough to run 2DTM, however, I've never tested a P4000 which are typically used for graphics visualization, not HPC. (To my knowledge anyway.) We can trouble shoot this, but it would be preferable to try to use a different card because there were several significant architectural changes between Pascal (**P**4000) and the Volta generation. Do you have access to any Volta or Turing gen cards?

**Comment by bHimes** [comment]
In case we do decide to try to track this down, the conditions do reproduce on bern, one of our machines that has a P4000: I get this output when running

```
>$ gpu_devices
GpuDevices is running...

CUDA-capable device count: 1

Device number: 0
  Device name: Quadro P4000
  Memory clock cate (KHz): 3802000
  Memory bus width (bits): 256
  Memory bandwidth (GB/s): 243.328000
  Number of multiprocessors: 14
  Threads per multiprocessor: 2048
  Memory on device (GB): 7.896362
  Free memory (GB): 6.462036

```

but when running TM i get

```
requesting 1 gpus
CUDA-capable device count: 1

No suitable GPU found. Terminating...
Failed Assert at /groups/himesb/cisTEM_downstream_bah/src/gpu/DeviceManager.cu:116
void DeviceManager::Init(int)

No suitable GPU found. Terminating...
Failed Assert at /groups/himesb/cisTEM_downstream_bah/src/gpu/DeviceManager.cu:116
void DeviceManager::Init(int)

```

**Comment by bencreekm** [comment]
Thanks for your quick response! I tried again with a GeForce RTX2080 and did not run into the same problem. The template match completed without any errors. However, using the tutorial dataset it found 0 peaks above threshold

**Comment by bHimes** [comment]
I would suspect your template - did you create a reference using all subunits or only one?

**Comment by bencreekm** [comment]
Ah yes. I had created the template only using one subunit. When I regenerated the template with all subunits it worked well! Thanks again for your help!
