### ISSUE TITLE
Measuring and applying CTF correction for images of tilted specimen using cisTEM alpha

### ISSUE THREAD

**Issue by rahelwoldeyes** [bHimes/cisTEM_docs#23]
**Is this related to**
 Tomography 

**Describe the solution you'd like**
Can you describe how one can using cisTEM alpha to measure and correct for the CTF in images of tilted specimen? 

**Describe alternatives you've considered**
I see the "determine sample tilt" option in the ctffind function, but I am not sure this is what activates tiling of images.  

**Additional context**
Thanks!

**Comment by bHimes** [comment]
Hi Rahel,

Yes you have it right. I suspect if you run it on a tilted image with this checked/unchecked you will confirm for yourself.

If you look at the job results, you'll see a tilt-axis/angle are reported. These are currently used inside cisTEM for ctf correction during SPA. 

Nothing yet implemented to export.
