### ISSUE TITLE
Updated alpha version

### ISSUE THREAD

**Issue by rahelwoldeyes** [bHimes/cisTEM_docs#24]
**Is this related to**
- [  ] Tomography 

**Describe the solution you'd like**
I downloaded the cistem alpha binary from (https://bhimes.github.io/cisTEM_docs/docs/sim/tutorials/get_cistem.html) . This version ( cisTEM_1_0aabb63_20210505.zip) seems to be missing the Wiener filter option under applyctf you describe in your tutorial. Can you update the binary? 

**Describe alternatives you've considered**
I tried to compile from source, but I think the instructions I have found are not up to date. 

**Additional context**

**Comment by jojoelfe** [comment]
Hi,

if you want the most cutting edge you can download builds from our continuous integration:

https://github.com/timothygrant80/cisTEM/actions

You probably want the binaries build with icpc, the most recent ones are here:

https://github.com/timothygrant80/cisTEM/suites/5868415203/artifacts/197972184

Hope this helps!

**Comment by rahelwoldeyes** [comment]
Hi,

Do you have a centos7 compatible version of the binaries? 

thank you!

**Comment by bHimes** [comment]
> Hi,
> 
> Do you have a centos7 compatible version of the binaries?
> 
> thank you!

Hi Rahel,

The alpha versions are only available for OS that are running on a more recent kernel. (centOS 7 is way past it's end of life.) There is a chance you or your sysadmin updated your kernel though, which can be checked with 
```bash
# you'll need a kernel >=5
$ uname -r
```
The other sticking point is the gnu implementation of the c++ standard library (glibc) which you can check with 
```bash
# you'll need glibc >= 2.27
$ ldd --version
```

You may create an issue to request better compilation instructions. We unfortunately will not be supporting older systems directly as this branch of the project is specifically for working on new advanced topics, which require new hardware/software.

**Comment by rahelwoldeyes** [comment]
Thank you Ben. 

The OS is Centos 7.9. The kernel and glibc versions are older than what the alpha requires. 

I will create an issue for better compilation instructions.
