### ISSUE TITLE
Compilation instructions for cisTEM

### ISSUE THREAD

**Issue by rahelwoldeyes** [bHimes/cisTEM_docs#25]
**Is this related to**
All
- [  ] Code development
- [  ] Single-particle cryoEM
- [  ]  In situ particle detection
- [  ] Simulation
- [  ] Tomography 

**Describe the solution you'd like**

Can you describe how one can compile cisTEM? 

**Describe alternatives you've considered**
The "building from source" instructions here (https://github.com/timothygrant80/cisTEM) doesn't seem up to date. I can't find the configure file. I see "configure.ac". Do I need to use automake? 

**Additional context**

**Comment by jojoelfe** [comment]
Hi,

yes you will need autotools and wxWidgets installed. You will also either need the intel compiler suite or g++ and fftw.

To generate the configure file run the `regenerate_project.b` script.

Best,

Johannes

**Comment by rahelwoldeyes** [comment]
Thanks Johannes. I will try it out. 

Best,
