### ISSUE TITLE
Images not in repository

### ISSUE THREAD

**Issue by jojoelfe** [bHimes/cisTEM_docs#3]
The images (icon etc. ) are not in the repository. Do you want to handle them outside of git?

A related questions is if we want to ship example micrographs for tutorials and whether they should get submitted into the repository?

**Comment by bHimes** [comment]
No large binaries in the repo. Once it is stable, and the images are not likely to change, maybe this is okay. For now, icons and other files should be shipped separately.

I put them on the lab drive page for now, linked from this [wik](https://github.com/bHimes/cisTEM_docs/wiki).
